language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"


services:
  - rabbitmq

install: python setup.py install

# command to run tests
script: tests/client_0_8/run_all.py